name: Ruby

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.5
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: |
          bundle exec rspec
